### ISSUE TITLE
Replace gd with imagick

### ISSUE THREAD

**Issue by yanbreu** [psmb/docker-neos-alpine#11]
It would be nice if imagick is installed by default too.
See Neos Install recommendation:
![Imgur](https://i.imgur.com/qjirNB7.png?1)

**Comment by dimaip** [comment]
Hey, thanks for your suggestion, but in my experience gd actually performs better. Can you verify that imagick actually works better for your with this image? If you ran some tests could you please share your results?

**Comment by yanbreu** [comment]
For me both is fine. I used both without any trouble. I just thought it would be better to use the recommended settings :smile:

**Comment by dimaip** [comment]
I'm just wondering if those recommendations are up to date. Would be nice to test it again.

**Comment by yanbreu** [comment]
Gd is fine i found some cases where imagick dont works but gd does. So I close this issue.
